# Generated by Django 5.1.6 on 2025-03-31 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productcategory_supermarket_supermarketproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='supermarket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supermarket'),
        ),
    ]
