# Generated by Django 5.1.6 on 2025-04-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_complaints_is_read_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarketorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supermarketorder',
            name='user',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('medicines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medicine')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supermarketproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flatoccupant')),
            ],
        ),
        migrations.RenameModel(
            old_name='SupermarketPayment',
            new_name='Payment',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Dispatched', 'Dispatched'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('tracking_history', models.JSONField(default=dict)),
                ('medicines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medicine')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supermarketproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.flatoccupant')),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app.order'),
        ),
        migrations.DeleteModel(
            name='SupermarketCart',
        ),
        migrations.DeleteModel(
            name='SupermarketOrder',
        ),
    ]
