# Generated by Django 5.1.6 on 2025-04-04 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_supermarketorder_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='app.flatoccupant')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='app.security')),
            ],
            options={
                'ordering': ['-last_message_time'],
                'unique_together': {('security', 'occupant')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('Security', 'Security'), ('Occupant', 'Occupant')], max_length=10)),
                ('sender_id', models.IntegerField()),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chatroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
